dependencies:
- name: prometheus
  condition: prometheus.enabled
  version: "14.9.1"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: grafana
  condition: grafana.enabled
  version: "6.16.13"
  repository: "https://grafana.github.io/helm-charts"
- name: loki
  condition: loki.enabled
  version: "2.6.0"
  repository: "https://grafana.github.io/helm-charts"
- name: tempo
  condition: tempo.enabled
  version: "0.7.7"
  repository: "https://grafana.github.io/helm-charts"
- name: fluent-bit
  condition: fluent-bit.enabled
  version: "0.19.1"
  repository: "https://fluent.github.io/helm-charts"