prometheus:
  enabled: true

  pushgateway:
    enabled: false
  server:
    fullnameOverride: prometheus
    service:
      # loadBalancerIP: "10.1.1.104"
      type: LoadBalancer 

grafana:
  enabled: true

  adminUser: admin
  adminPassword: aspenmesh
  dashboards:
    default:
      kubernetes-cluster:
        gnetId: 7249
        revision: 1
        datasource: Prometheus
      kubernetes-cluster-monitoring-prometheus:
        gnetId: 1621
        datasource: Prometheus
      prometheus-stats:
        gnetId: 2
        revision: 2
        datasource: Prometheus
      istio-mesh:
        gnetId: 7639
        revision: 92
        datasource: Prometheus
      istio-service:
        gnetId: 7636
        revision: 92
        datasource: Prometheus
      istio-workload:
        gnetId: 7630
        revision: 92
        datasource: Prometheus
      istio-performance:
        gnetId: 11829
        revision: 92
        datasource: Prometheus
      istio-controlplane:
        gnetId: 7645
        revision: 92
        datasource: Prometheus
      istio-loki:
        gnetId: 14876
        revision: 2
        datasource: Loki
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki.istio-system.svc.cluster.local:3100
          access: proxy
          orgId: 1
          uid: loki
          jsonData:
            derivedFields:
              - datasourceName: Tempo
                matcherRegex: "traceID=(\\w+)"
                name: TraceID
                url: "$${__value.raw}"
                datasourceUid: tempo
          isDefault: false
        - name: Prometheus
          type: prometheus
          url: http://prometheus.istio-system.svc.cluster.local:80
          access: proxy
          orgId: 1
          uid: prometheus
          isDefault: true
        - name: Tempo
          type: tempo
          url: http://tempo.istio-system.svc:3100
          access: proxy
          orgId: 1
          uid: tempo
          isDefault: false
  persistence:
    enabled: true
  service:
    # loadBalancerIP: "10.1.1.105"
    type: LoadBalancer


loki:
  enabled: true

  persistence:
    enabled: true
  service:
    # loadBalancerIP: "10.1.1.106"
    type: LoadBalancer

tempo:
  enabled: true

  persistence:
    enabled: true
  tempo:
    extraArgs:
      "distributor.log-received-traces": true
    receivers:
      zipkin:
      otlp:
        protocols:
          http:
          grpc:

fluent-bit:
  enabled: true

  logLevel: trace
  config:
    service: |
      [SERVICE]
          Flush 1
          Daemon Off
          Log_Level trace
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*istio-proxy*.log
          Parser cri
          Tag kube.*
          Mem_Buf_Limit 5MB
    outputs: |
      [OUTPUT]
          name loki
          match *
          host loki.istio-system.svc
          port 3100
          tenant_id ""
          labels job=fluentbit
          label_keys $trace_id
          auto_kubernetes_labels on
    customParsers: |
      [PARSER]
          Name cri
          Format regex
          Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
          Time_Key    time
          Time_Format %Y-%m-%dT%H:%M:%S.%L%z
