dependencies:
- name: prometheus
  condition: prometheus.enabled
  version: "14.9.1"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: grafana
  condition: grafana.enabled
  version: "6.16.13"
  repository: "https://grafana.github.io/helm-charts"
- name: jaeger
  condition: jaeger.enabled
  version: "0.47.0"
  repository: "https://jaegertracing.github.io/helm-charts"
- name: kiali-server
  condition: kiali-server.enabled
  version: "v1.41.0"
  repository: "https://kiali.org/helm-charts"