# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
prometheus:
  enabled: true
  fullnameOverride: prometheus

  alertmanager:
    fullnameOverride: prometheus-alertmanager
  kubeStateMetrics:
    enabled: true
  kube-state-metrics:
    fullnameOverride: kube-state-metrics
  nodeExporter:
    fullnameOverride: prometheus-node-exporter
  pushgateway:
    fullnameOverride: prometheus-pushgateway
    enabled: false
  server:
    fullnameOverride: prometheus
    service:
      type: LoadBalancer 


# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  enabled: true
  fullnameOverride: grafana

  adminUser: admin
  adminPassword: aspenmesh
  dashboards:
    default:
      kubernetes-cluster:
        gnetId: 7249
        revision: 1
        datasource: Prometheus
      node-exporter:
        gnetId: 1860
        revision: 23
        datasource: Prometheus
      kubernetes-cluster-monitoring-prometheus:
        gnetId: 1621
        datasource: Prometheus
      prometheus-stats:
        gnetId: 2
        revision: 2
        datasource: Prometheus
      istio-mesh:
        gnetId: 7639
        revision: 92
        datasource: Prometheus
      istio-service:
        gnetId: 7636
        revision: 92
        datasource: Prometheus
      istio-workload:
        gnetId: 7630
        revision: 92
        datasource: Prometheus
      istio-performance:
        gnetId: 11829
        revision: 92
        datasource: Prometheus
      istio-controlplane:
        gnetId: 7645
        revision: 92
        datasource: Prometheus
      jaeger:
        gnetId: 10001
        revision: 2
        datasource: Prometheus
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus:80
          access: proxy
          orgId: 1
          uid: prometheus
          isDefault: true
  persistence:
    enabled: true
  service:
    type: LoadBalancer


# https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml
jaeger:
  enabled: true
  fullnameOverride: jaeger
  agent:
    fullnameOverride: jaeger-agent-bond
  collector:
    fullnameOverride: jaeger-collector
    service:
      zipkin:
        port: 9411
  query:
    fullnameOverride: jaeger-query
    service:
      type: LoadBalancer
  storage:
    cassandra:
      nameOverride: cassandra
  # https://github.com/helm/charts/tree/master/incubator/cassandra
  cassandra:
    fullnameOverride: cassandra


# https://github.com/kiali/helm-charts/blob/master/kiali-server/values.yaml
kiali-server:
  enabled: true
  fullnameOverride: kiali

  istio_namespace: istio-system
  auth:
    strategy: anonymous
  deployment:
    service_type: LoadBalancer
  external_services:
    istio:
      component_status:
        components:
        - app_label: istiod
          is_core: true
          is_proxy: false
        - app_label: istio-ingressgateway
          is_core: true
          is_proxy: true
        - app_label: istio-eastwestgateway
          is_core: false
          is_proxy: true
        - app_label: istio-egressgateway
          is_core: false
          is_proxy: true
    grafana:
      auth:
        password: aspenmesh
        username: admin
      in_cluster_url: http://grafana:80
      url: http://grafana.aspendemo.org
    prometheus:
      url: http://prometheus:80
    server:
      port: 80
    tracing:
      in_cluster_url: http://jaeger-query:80
      url: http://jaeger.aspendemo.org
      use_grpc: false
      whitelist_istio_system: ["jaeger-query", "istio-ingressgateway", "istio-eastwestgateway", "istio-egressgateway"]
