prometheus:
  enabled: true

  pushgateway:
    enabled: false
  server:
    fullnameOverride: prometheus
    service:
      # loadBalancerIP: "10.1.1.104"
      type: LoadBalancer 

grafana:
  enabled: true

  adminUser: admin
  adminPassword: aspenmesh
  dashboards:
    default:
      kubernetes-cluster:
        gnetId: 7249
        revision: 1
        datasource: Prometheus
      kubernetes-cluster-monitoring-prometheus:
        gnetId: 1621
        datasource: Prometheus
      prometheus-stats:
        gnetId: 2
        revision: 2
        datasource: Prometheus
      istio-mesh:
        gnetId: 7639
        revision: 92
        datasource: Prometheus
      istio-service:
        gnetId: 7636
        revision: 92
        datasource: Prometheus
      istio-workload:
        gnetId: 7630
        revision: 92
        datasource: Prometheus
      istio-performance:
        gnetId: 11829
        revision: 92
        datasource: Prometheus
      istio-controlplane:
        gnetId: 7645
        revision: 92
        datasource: Prometheus
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus.{{ template "kiali-stack.namespace" . }}:80
          access: proxy
          orgId: 1
          uid: prometheus
          isDefault: true
  persistence:
    enabled: true
  service:
    # loadBalancerIP: "10.1.1.105"
    type: LoadBalancer

jaeger:
  enabled: true

  agent:
    fullnameOverride: jaeger-agent-bond
  collector:
    service:
      zipkin:
        port: 9411
  query:
    service:
      # loadBalancerIP: "10.1.1.107"
      type: LoadBalancer

kiali-server:
  enabled: true

  istio_namespace: istio-system
  auth:
    strategy: anonymous
  deployment:
    service_type: LoadBalancer
    # additional_service_yaml: { "loadBalancerIP": "10.1.1.103" }
  external_services:
    istio:
      component_status:
        components:
        - app_label: istiod
          is_core: true
          is_proxy: false
        - app_label: istio-ingressgateway
          is_core: true
          is_proxy: true
        - app_label: istio-eastwestgateway
          is_core: false
          is_proxy: true
        - app_label: istio-egressgateway
          is_core: false
          is_proxy: true
    grafana:
      auth:
        password: aspenmesh
        username: admin
      in_cluster_url: http://grafana.{{ template "kiali-stack.namespace" . }}:80
      url: http://grafana.aspendemo.org
    prometheus:
      url: http://prometheus.{{ template "kiali-stack.namespace" . }}:80
    tracing:
      in_cluster_url: http://jaeger-query.{{ template "kiali-stack.namespace" . }}:80
      url: http://jaeger.aspendemo.org
      use_grpc: false
      whitelist_istio_system: ["jaeger-query", "istio-ingressgateway", "istio-eastwestgateway", "istio-egressgateway"]
