apiVersion: v2
name: istio-nginx-kic
description: A Helm chart for Istio with Nginx+ based KIC (K8s Ingress Controller)

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.11.3"

home: https://aspenmesh.io
sources:
- https://github.com/aspenmesh/helm-charts
maintainers:
- name: Bart Van Bos
  email: b.vanbos@f5.com
engine: gotpl

dependencies:
- name: base
  condition: base.enabled
  version: "1.11.3"
  repository: "https://aspenmesh.github.io/helm-charts"
- name: istio-discovery
  condition: istio-discovery.enabled
  version: "1.11.3"
  repository: "https://aspenmesh.github.io/helm-charts"
- name: nginx-ingress
  condition: nginx-ingress.enabled
  version: "0.9.3" # "0.11.2"
  repository: "https://helm.nginx.com/stable"
- name: grafana
  condition: grafana.enabled
  version: "6.16.13"
  repository: "https://grafana.github.io/helm-charts"
- name: jaeger
  condition: jaeger.enabled
  version: "0.47.0"
  repository: "https://jaegertracing.github.io/helm-charts"
- name: kiali-server
  condition: kiali-server.enabled
  version: "v1.41.0"
  repository: "https://kiali.org/helm-charts"
