apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata: 
  name: istiocontrolplane
  namespace: istio-system
spec:
  components: 
    egressGateways: 
    - enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - istio-egressgateway
              topologyKey: "kubernetes.io/hostname"
        hpaSpec:
          minReplicas: 2
          maxReplicas: 3
      name: istio-egressgateway
    ingressGateways: 
    - enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - istio-ingressgateway
              topologyKey: "kubernetes.io/hostname"
        hpaSpec:
          minReplicas: 2
          maxReplicas: 3
        service: 
          type: LoadBalancer
      name: istio-ingressgateway
    pilot:
      enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - istiod
              topologyKey: "kubernetes.io/hostname"
        hpaSpec:
          minReplicas: 2
          maxReplicas: 3
  meshConfig:
    accessLogEncoding: TEXT
    accessLogFile: /dev/stdout
    accessLogFormat: "{\"authority\":\"%REQ(:AUTHORITY)%\",\"bytes_received\":\"%BYTES_RECEIVED%\",\"bytes_sent\":\"%BYTES_SENT%\",\"connection_termination_details\":\"%CONNECTION_TERMINATION_DETAILS%\",\"downstream_local_address\":\"%DOWNSTREAM_LOCAL_ADDRESS%\",\"downstream_peer_cert_v_end\":\"%DOWNSTREAM_PEER_CERT_V_END%\",\"downstream_peer_cert_v_start\":\"%DOWNSTREAM_PEER_CERT_V_START%\",\"downstream_remote_address\":\"%DOWNSTREAM_REMOTE_ADDRESS%\",\"downstream_tls_cipher\":\"%DOWNSTREAM_TLS_CIPHER%\",\"downstream_tls_version\":\"%DOWNSTREAM_TLS_VERSION%\",\"duration\":\"%DURATION%\",\"hostname\":\"%HOSTNAME%\",\"istio_policy_status\":\"%DYNAMIC_METADATA(istio.mixer:status)%\",\"method\":\"%REQ(:METHOD)%\",\"path\":\"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\",\"protocol\":\"%PROTOCOL%\",\"request_duration\":\"%REQUEST_DURATION%\",\"request_id\":\"%REQ(X-REQUEST-ID)%\",\"requested_server_name\":\"%REQUESTED_SERVER_NAME%\",\"response_code\":\"%RESPONSE_CODE%\",\"response_code_details\":\"%RESPONSE_CODE_DETAILS%\",\"response_duration\":\"%RESPONSE_DURATION%\",\"response_tx_duration\":\"%RESPONSE_TX_DURATION%\",\"response_flags\":\"%RESPONSE_FLAGS%\",\"route_name\":\"%ROUTE_NAME%\",\"start_time\":\"%START_TIME%\",\"trace_id\":\"%REQ(x-b3-traceid)%\",\"upstream_cluster\":\"%UPSTREAM_CLUSTER%\",\"upstream_host\":\"%UPSTREAM_HOST%\",\"upstream_local_address\":\"%UPSTREAM_LOCAL_ADDRESS%\",\"upstream_service_time\":\"%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%\",\"upstream_transport_failure_reason\":\"%UPSTREAM_TRANSPORT_FAILURE_REASON%\",\"user_agent\":\"%REQ(USER-AGENT)%\",\"x_forwarded_for\":\"%REQ(X-FORWARDED-FOR)%\"}\n"
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
        max_path_tag_length: 99999
        zipkin:
          address: tempo.monitoring:9411
  profile: default
