apiVersion: v2
name: elastic-stack
description: A Helm chart for Istio Monitoring with Elastic Search, Kibana, APM Server and Filebeat

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.11.3"

home: https://aspenmesh.io
sources:
- https://github.com/aspenmesh/helm-charts
maintainers:
- name: Bart Van Bos
  email: b.vanbos@f5.com
engine: gotpl

dependencies:
- name: elasticsearch
  condition: elasticsearch.enabled
  version: "7.15.0"
  repository: "https://helm.elastic.co"
- name: kibana
  condition: kibana.enabled
  version: "7.15.0"
  repository: "https://helm.elastic.co"
- name: apm-server
  condition: apm-server.enabled
  version: "7.15.0"
  repository: "https://helm.elastic.co"
- name: filebeat
  condition: filebeat.enabled
  version: "7.15.0"
  repository: "https://helm.elastic.co"
- name: metricbeat
  condition: metricbeat.enabled
  version: "7.15.0"
  repository: "https://helm.elastic.co"
- name: logstash
  condition: logstash.enabled
  version: "7.15.0"
  repository: "https://helm.elastic.co"
- name: opentelemetry-collector
  condition: opentelemetry-collector.enabled
  version: "0.6.0"
  repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
